export const courses = [
  {
    id: 'c1',
    title: 'React Fundamentals',
    instructor: 'Jane Cooper',
    category: 'Web Development',
    level: 'Beginner',
    duration: '6h 30m',
    lessons: 24,
    rating: 4.8,
    students: 12400,
    price: 0,
    thumbnail: 'https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=600',
    description:
      'Learn the basics of React including components, props, state, and hooks.',
    tags: ['React', 'JavaScript', 'Frontend'],
  },
  {
    id: 'c2',
    title: 'Advanced TailwindCSS',
    instructor: 'Marcus Lee',
    category: 'Design',
    level: 'Intermediate',
    duration: '4h 10m',
    lessons: 18,
    rating: 4.7,
    students: 8300,
    price: 29,
    thumbnail: 'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?w=600',
    description:
      'Build beautiful, responsive UIs with utility-first CSS and Tailwind v4.',
    tags: ['Tailwind', 'CSS', 'UI'],
  },
  {
    id: 'c3',
    title: 'Node.js for Backend',
    instructor: 'Priya Singh',
    category: 'Backend',
    level: 'Intermediate',
    duration: '9h 00m',
    lessons: 32,
    rating: 4.6,
    students: 15200,
    price: 49,
    thumbnail: 'https://images.unsplash.com/photo-1516116216624-53e697fedbea?w=600',
    description: 'Master Node.js, Express, and REST API design for production apps.',
    tags: ['Node', 'Express', 'API'],
  },
  {
    id: 'c4',
    title: 'Python Data Science',
    instructor: 'Alex Chen',
    category: 'Data Science',
    level: 'Beginner',
    duration: '12h 45m',
    lessons: 40,
    rating: 4.9,
    students: 22100,
    price: 59,
    thumbnail: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=600',
    description:
      'Analyze data, build models, and visualize insights using Python and pandas.',
    tags: ['Python', 'Data', 'ML'],
  },
  {
    id: 'c5',
    title: 'UI/UX Design Principles',
    instructor: 'Sara Ahmed',
    category: 'Design',
    level: 'Beginner',
    duration: '5h 20m',
    lessons: 20,
    rating: 4.5,
    students: 6100,
    price: 19,
    thumbnail: 'https://images.unsplash.com/photo-1559028012-481c04fa702d?w=600',
    description: 'Design thinking, wireframes, prototyping and user research basics.',
    tags: ['Design', 'Figma', 'UX'],
  },
  {
    id: 'c6',
    title: 'Docker & Kubernetes',
    instructor: 'David Kim',
    category: 'DevOps',
    level: 'Advanced',
    duration: '8h 15m',
    lessons: 28,
    rating: 4.7,
    students: 9400,
    price: 69,
    thumbnail: 'https://images.unsplash.com/photo-1605745341112-85968b19335b?w=600',
    description: 'Containerize applications and orchestrate them with Kubernetes.',
    tags: ['Docker', 'K8s', 'DevOps'],
  },
];

export const enrollments = [
  { courseId: 'c1', progress: 72, lastAccessed: '2026-04-21', completedLessons: 17 },
  { courseId: 'c3', progress: 35, lastAccessed: '2026-04-18', completedLessons: 11 },
  { courseId: 'c4', progress: 100, lastAccessed: '2026-04-10', completedLessons: 40 },
  { courseId: 'c5', progress: 12, lastAccessed: '2026-04-23', completedLessons: 2 },
];
